POST http://10.0.76.177:8080/api/v1/hook/github
Content-Type: application/json

{"name": "Spring in Action", "price": 1.00, "author": "Craig Walls"}

###
###
GET http://127.0.0.1:8080/api/v1/hook/github
Accept: application/json

###
